# SAM configuration file with multiple environments
version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fartooyoung-local"
s3_bucket = "fartooyoung-backend-local"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=local",
    "SecretsManagerArn="
]
confirm_changeset = false

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "fartooyoung-staging"
s3_bucket = "fartooyoung-backend-staging"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=staging",
    "DynamoDBEndpoint=\"\"",
    "SecretsManagerArn=arn:aws:secretsmanager:us-east-1:538781441544:secret:fartooyoung-staging-secrets-BjIpQD"
]
confirm_changeset = false

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "fartooyoung-production"
s3_bucket = "fartooyoung-backend-production"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=production",
    "DynamoDBEndpoint=\"\"",
    "SecretsManagerArn=arn:aws:secretsmanager:us-east-1:538781441544:secret:fartooyoung-production-secrets-tEmB4i"
]
confirm_changeset = false
